---
apiVersion: v1
kind: Namespace
metadata:
  name: fma-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fma-nginx
  namespace: fma-demo
  labels:
    app: fma-nginx
spec:
  selector:
    matchLabels:
      app: fma-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: fma-nginx
    spec:
      containers:
      - name: fma-nginx
        image: bitnami/nginx
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name: fma-nginx
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fma-nginx
  namespace: fma-demo
spec:
  selector:
    app: fma-nginx
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: fma-nginx
    protocol: TCP
    port: 80
    targetPort: 8080
