apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fma-fleetdemo-metallb
  namespace: fleet-default
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
  - metallb
  repo: https://github.com/fm4991/fleet-demo.git
  targets:
  - clusterSelector:
      matchLabels:
        metallb: "yes"
    name: metallb
diff:
  comparePatches:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: addresspools.metallb.io
    operations:
    - {"op": "remove", "path":"/spec/conversion/webhook/clientConfig/caBundle"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    operations:
    - {"op": "remove", "path":"/spec/conversion/webhook/clientConfig/caBundle"}
